In [1]:
import numpy as np

In [2]:
np.random.seed(42)

input yang dihitung adalah jumlah kolom, tapi dalam komputasi ini kita gunakan juml;ah baris

setiap vektor yang di inisiasi harus dalam bentuk baris x kolom

In [3]:
x = np.random.rand(1,1)
y = 12*x + 8

print(x)
print(y)

[[0.37454012]]
[[12.49448143]]


In [4]:
x.shape

(1, 1)

$$z = \sigma \sum_{i=1}^{n}\left ( \vec{x_i}\vec{w_i} \right ) + b$$

$$MSE = \frac{1}{n}\sum_{i = 1}^{n}(Y_i - \hat{Y_i})^2$$

W' = W + \alpha \frac{}{}

In [5]:
class Neuron:
    
    def __init__(self, input_size, learning_rate, epoch):
        """
            input_size = jumlah baris dari input
            
        """
        self.w = np.random.rand(input_size, 1)
        self.bias = np.random.rand(1, 1)
        self.learning_rate = learning_rate
        self.epoch = epoch
        
    # method for feedforward
    def f_forward(self, inp):
        """
            inp = data input
        """
        result = inp.T.dot(self.w) + self.bias
        return result
    
    # mean squared error
    def loss(self, x, y):
        """
            x = data input
            y = real output
        """
        a = self.f_forward(x)
        L = (a - y)**2
        return L
    
    # backpropagation
    def backward(self, x, y):
        """
            x = data input
            y = real output
        """
        a = self.f_forward(x)
        
        dw = 2.*(a - y) * x.T
        db = 2.*(a - y) * 1.
        
        # gradient descent
        self.w = self.w - self.learning_rate * dw.T
        self.bias = self.bias - self.learning_rate * db.T
        
        return self.w, self.bias
    
    def train(self, x, y):
        """
            x = data input
            y = real output
        """
        acc = []
        losss = []
        for j in range(self.epoch):
            l = []
            for i in range(x.shape[0]):
                l = self.loss(x, y)
                w1, b1 = self.backward(x, y)
            print("epochs:", j + 1, "======== acc:", (1 - (sum(l)/x.shape[0]))*100)
            acc.append((1 - (sum(l)/x.shape[0]))*100)
            losss.append(sum(l)/x.shape[0])
        return (acc, losss, w1, b1)

In [6]:
neuron = Neuron(1, 0.5, 10)
a, b, c, d = neuron.train(x, y)

epochs: 1 ======== acc: [-12910.61168865]
epochs: 2 ======== acc: [-156.03013845]
epochs: 3 ======== acc: [94.96169486]
epochs: 4 ======== acc: [99.9008534]
epochs: 5 ======== acc: [99.99804894]
epochs: 6 ======== acc: [99.99996161]
epochs: 7 ======== acc: [99.99999924]
epochs: 8 ======== acc: [99.99999999]
epochs: 9 ======== acc: [100.]
epochs: 10 ======== acc: [100.]


In [7]:
c, d

(array([[4.69729921]]), array([[10.73515439]]))

In [8]:
b

[array([130.10611689]),
 array([2.56030138]),
 array([0.05038305]),
 array([0.00099147]),
 array([1.95106267e-05]),
 array([3.83941091e-07]),
 array([7.55540885e-09]),
 array([1.48679587e-10]),
 array([2.92580058e-12]),
 array([5.75755504e-14])]

In [9]:
print("aku adalah superman")

aku adalah superman
